apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prusalink-watcher
  name: prusalink-watcher
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prusalink-watcher
  template:
    metadata:
      labels:
        app: prusalink-watcher
    spec:
      containers:
      - name: prusalink-watcher
        image: ghcr.io/mmaschenk/printwatcher:0.4
        envFrom:
        - configMapRef:
            name: environment
        resources:
          limits:
            memory: "100Mi"
            cpu: "50m"
        command: [ "python" ]
        args: [ "-u", "/watcher.py"]
        volumeMounts:
        - mountPath: /config
          name: watcherconfig
      volumes:
      - name: watcherconfig
        configMap:
          name: watcherconfig
